server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/greenwalkdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
      #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        # show_sql: true
#        format_sql: true
#        dialect: org.hibernate.dialect.H2Dialect
#        default_batch_fetch_size: 100
#    open-in-view: false

#  output:
#    ansi:
#      enabled: always

  mail:
    host: smtp.gmail.com
    port: 587
    username: efowdwd@gmail.com
    password: gtiwxjzjbbihsfxq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분

    #  redis:
    #    host: localhost
    #    port: 6379

jwt:
  secretKey: "dkfjklfdfdadfadf23f24f30298nf2ndkfjld2jkflddfa3fdf2fe43fejl34fklje23kj"
  access:
    expiration: 3600000 # 1시간(60분) (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h))
    header: "Authorization"
  refresh:
    expiration: 1209600000 #  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> 하루) * 14(2주))
    header: "Authorization-refresh"


logging:
  level:
    '[org.springframework.boot.web]': DEBUG

# debug info warn error
